<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class KxUserBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $user_id    
 * @property $user_name    
 * @property $user_password    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class KxUserBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'kx_user';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'user_id';

    /**
     * @return array
     */
    public static function getFields()
    {
        return [
            'user_id',
            'user_name',
            'user_password',
            'status',
            'create_time',
            'update_time',
        ];
    }
}

