<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class ThItemsBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $id    
 */
class ThItemsBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'th_items';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'id';

    /**
     * @return array
     */
    public static function getFields()
    {
        return [
            'id',
        ];
    }
}

