<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class ThMenuBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $menu_id    
 * @property $menu_style    
 * @property $menu_name    
 * @property $menu_href    
 * @property $parent_id    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class ThMenuBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'th_menu';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'menu_id';

    /**
     * @return array
     */
    public static function getFields()
    {
        return [
            'menu_id',
            'menu_style',
            'menu_name',
            'menu_href',
            'parent_id',
            'status',
            'create_time',
            'update_time',
        ];
    }
}

