<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class ThPageConfigBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $config_id    
 * @property $page_id    
 * @property $config_category    
 * @property $config_type    
 * @property $config_value    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class ThPageConfigBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'th_page_config';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'config_id';

    /**
     * @return array
     */
    public static function getFields()
    {
        return [
            'config_id',
            'page_id',
            'config_category',
            'config_type',
            'config_value',
            'status',
            'create_time',
            'update_time',
        ];
    }
}

