<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class ThSampleBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $sample_id    
 * @property $sample_type    
 * @property $sample_name    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class ThSampleBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'th_sample';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'sample_id';

    /**
     * @return array
     */
    public static function getFields()
    {
        return [
            'sample_id',
            'sample_type',
            'sample_name',
            'status',
            'create_time',
            'update_time',
        ];
    }
}

