<?php

namespace App\Models;


use App\Models\Base\KxUserBase;

/**
 * @package App\Models
 * Class KxUser
 *
 * Generated by 'php artisan model:create'
 */
class KxUser extends KxUserBase
{
    public function toArray()
    {
        $array = parent::toArray();
        return $array;
    }

}

