<?php

namespace App\Models;


use App\Models\Base\ThListParamBase;

/**
 * @package App\Models
 * Class ThListParam
 *
 * Generated by 'php artisan model:create'
 */
class ThListParam extends ThListParamBase
{

}

