<?php

namespace App\Models;


use App\Models\Base\ThPageConfigBase;

/**
 * @package App\Models
 * Class ThPageConfig
 *
 * Generated by 'php artisan model:create'
 */
class ThPageConfig extends ThPageConfigBase
{
    public function toArray()
    {
        $array = parent::toArray();
        return $array;
    }
}

