<?php

namespace App\Models;


use App\Models\Base\ThSampleBase;

/**
 * @package App\Models
 * Class ThSample
 *
 * Generated by 'php artisan model:create'
 */
class ThSample extends ThSampleBase
{

}

